Improve English of README
voxpupuli/puppet-fetchcrl pull request #99
Opened 2023-08-23 07:56 UTC by traylenator

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2023-08-23 17:49 UTC, olifre approved these changes
LGTM :+1:

2023-08-23 19:24 UTC, kenyon requested changes

2023-08-23 19:24 UTC, kenyon commented on README.md
> +This is the fetchcrl module it configures fetch-crl version 3 wherever it can.
```suggestion
This is the fetchcrl Puppet module. It configures fetch-crl version 3 wherever it can.
```

2023-08-23 19:43 UTC, olifre commented on README.md
> +This is the fetchcrl module it configures fetch-crl version 3 wherever it can.
Indeed, that reads more fluent :+1: .

2023-08-24 09:20 UTC, bastelfreak approved these changes

2023-08-24 14:37 UTC, merged